version: '3.8'

services:
  code-judger:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - cargo-cache:/root/.cargo/registry
      - target-cache:/app/target
    environment:
      - RUST_BACKTRACE=1
      - CARGO_TARGET_DIR=/app/target
    command: cargo run --release
    networks:
      - judging-network
    ports:
      - "50052:50052"

networks:
  judging-network:
    external: true

volumes:
  cargo-cache:
  target-cache: 